### PR TITLE
Adding v font wght & Reverting to old font stacks

### PR DESCRIPTION
**Pull request by mhewson**
Adding a `font-variation-settings: "wght" XXX;` following the `font-weight: XXX` in the typography mixins so our variable font will work properly

Context:
[Variable fonts guide](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide) [#Weight](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#Weight)
[v-fonts.com examples](https://v-fonts.com/)

### CODE REVIEW

**Comment by arniebradfo** [comment]
Should the `@font-face` be a token mixin too?

Maybe we have the tokens:
```scss
$cdr-text-font-sans-name: "Graphik";
$cdr-text-font-sans-src: 
	url("//satchel.rei.com/media/font/Graphik/Graphik-VF/Graphik-VF-Web.woff2") format("woff2"),
	url("//satchel.rei.com/media/font/Graphik/Graphik-VF/Graphik-VF-Web.woff")  format("woff");

$cdr-text-font-serif-name: "Stuart";
$cdr-text-font-serif-src: 
	url("//satchel.rei.com/media/font/REI_Stuart/REI_Stuart-VF/REIStuart-VF-Web.woff2") format("woff2"),
	url("//satchel.rei.com/media/font/REI_Stuart/REI_Stuart-VF/REIStuart-VF-Web.woff")  format("woff");

```

and combine those into and `@font-face` mixin? something like:

```scss
@mixin cdr-text-font-face-sans {
    font-family:  $cdr-text-font-sans-name;
    src:          $cdr-text-font-sans-src;
}

@mixin cdr-text-font-face-serif {
    font-family:  $cdr-text-font-serif-name;
    src:          $cdr-text-font-serif-src;
}
```

What do yall think?

**Comment by mhewson** [comment]
Yea I don't think that the ask is to provide an asset but a mixin like we are with other type to ensure future name changes all happen in tokens

**Comment by arniebradfo** [comment]
@lancetharper the current mixins include the `font-weight` fallback, but I forgot to add it to the legacy/deprecated mixins...

they look like:
```scss
@mixin cdr-text-heading-400() {
  ...
  font-weight: 600;
  font-variation-settings: "wght" 600;
  ...
}
```

**Comment by lancetharper** [comment]
Sounds like this needs to be discussed

> @lancetharper the current mixins include the `font-weight` fallback, but I forgot to add it to the legacy/deprecated mixins...
> 
> they look like:
> 
> ```css-scss
> @mixin cdr-text-heading-400() {
>   ...
>   font-weight: 600;
>   font-variation-settings: "wght" 600;
>   ...
> }
> ```

@arniebradfo I'm talking about a font-family fallback. We would need to provide @font-face declarations for both variable fonts and normal web fonts for IE too.

That means we need different names for them i.e. "Stuart VF"/"Stuart Regular"

**Comment by arniebradfo** [comment]
@lancetharper 
ahh. I see, in that case, `font-weight` is supposed to map to `wght`

from https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#Weight
> [font-weight values] are still applied when dealing with non-variable or variable fonts, but with variable ones, any number from 1 to 1000 is now valid.

I don't know if this will help with ie though. maybe test it with the variable font first.

**Comment by arniebradfo** [comment]
If you want to revert adding the font-variation-settings to deprecated tokens, the edits were made in these two commits: 
- [adding variation-settings to deprecated fonts](https://github.com/rei/rei-cedar-tokens/pull/61/commits/ec952bbb7c7d692794d557bb9f9d425e1c2a0e91) - maple, redwood, spruce
- [adding variation-settings to deprecated fonts 2](https://github.com/rei/rei-cedar-tokens/pull/61/commits/77d9c8ad4588e1107e2e834fd4a91b755382bfce) - header 1-6

**Comment by arniebradfo** [comment]
we don't need font wght

**Pull request closed without merging**
