### PR TITLE
membership palette v1

### PR DESCRIPTION
**Pull request by mhewson**
Here is v1 of our membership tokens 
- https://airtable.com/appqxOlfAwQxmBndE/shrgaA5Y2GRXJRGnw/tbl6wsQLStdXZ0hEo

### CODE REVIEW

**Comment by sikhote** [comment]
To poke and prod—are these colors not for global use, only for the rei site? Do they get picked up and used within say, the doc site, in the same way as global? I'm not sure what the downstream effects are of the themes since I have not dug into them as much.

**Comment by mhewson** [comment]
> To poke and prod—are these colors not for global use, only for the rei site? Do they get picked up and used within say, the doc site, in the same way as global? I'm not sure what the downstream effects are of the themes since I have not dug into them as much.

Its an interesting thought, we designed palettes to be unique to a theme. While the doc site may need to display the rei.com palette as an example of how it is used within REI the doc site itself does not have a membership palette as there are no native doc site use cases to build anything using that palette.
It does however have a supported palette, knockout, which is unique to that theme.

our global tokens are the generic bases and all generics are distributed to all themes - this needs so refinement especially as we move to reduce the amount of component specific tokens. Today I would say that all alias tokens are shared globally to all themes 
Themes can modify the alias tokens mapping new options specific to the theme
Themes can add new alias tokens specific to the theme
Themes can extend options 

palettes are enabled to map new values to alias and component specific tokens but are not allowed to create unidentified tokens that do not exist in the global space.

**Comment by sikhote** [comment]
Some of the colors are being placed into `platform-tokens.json` within the `misc` category...checking more into it, but that was causing some oddness on the doc site.

**Comment by sikhote** [comment]
Looks good here:
https://cedar-site-nuxt-19d184.gitlab.io/

**Review by sikhote — APPROVED** [review]

**Pull request merged**
